@startuml Chargé de Stock
left to right direction
skinparam packageStyle rectangle

actor "Chargé de Stock" as stock

rectangle "StoreManager Pro" {
rectangle "Approvisionnements" {
      usecase " consulter statistique" as UC10

    usecase "Consulter Coût Total des Entrées" as UC10_I1
    usecase "Consulter Bons de Réception (BL)" as UC10_I2
    usecase "Consulter Fournisseurs Actifs" as UC10_I3
    usecase "Consulter Bordereaux de Livraison (Réceptions)" as UC10_I4

    usecase "Voir Ligne" as UC10_E1
    usecase "Confirmer Réception" as UC10_E2

    UC10 ..> UC10_I1 : <<include>>
    UC10 ..> UC10_I2 : <<include>>
    UC10 ..> UC10_I3 : <<include>>

    UC10_E1 ..> UC10_I4 : <<extend>>
    UC10_E2 ..> UC10_I4 : <<extend>>
  }
   rectangle "Produits & Tiers" {
      usecase " consulter statistique" as UC11

    usecase "Consulter Valeur Totale Stock" as UC11_I1
    usecase "Consulter Articles au Catalogue" as UC11_I2
    usecase "Consulter Clients Enregistrés" as UC11_I3

    usecase "Ajouter Produits" as UC11_E1
    usecase "Ajouter Clients" as UC11_E2
    usecase "Ajouter Fournisseurs" as UC11_E3

    usecase "Consulter Catalogue Produits" as UC11_E1_I1
    usecase "Filtrer par Nom (Produits)" as UC11_E1_I2

    usecase "Lister Clients" as UC11_E2_I1
    usecase "Filtrer par Nom (Clients)" as UC11_E2_I2

    usecase "Consulter Catalogue Fournisseurs" as UC11_E3_I1
    usecase "Filtrer par Nom (Fournisseurs)" as UC11_E3_I2

    UC11 ..> UC11_I1 : <<include>>
    UC11 ..> UC11_I2 : <<include>>
    UC11 ..> UC11_I3 : <<include>>

   

    UC11_E1 ..> UC11_E1_I1 : <<include>>
    UC11_E1 ..> UC11_E1_I2 : <<include>>

    UC11_E2 ..> UC11_E2_I1 : <<include>>
    UC11_E2 ..> UC11_E2_I2 : <<include>>

    UC11_E3 ..> UC11_E3_I1 : <<include>>
    UC11_E3 ..> UC11_E3_I2 : <<include>>
  }
  
}
stock --> UC10
stock --> UC10_I4
stock --> UC11
stock --> UC11_E1
stock --> UC11_E2
stock --> UC11_E3

@enduml